# Generated by Django 2.2.4 on 2019-08-28 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_type', models.CharField(choices=[(users.models.AdminType('SUPER_ADMIN'), 'SUPER_ADMIN'), (users.models.AdminType('ADMIN'), 'ADMIN'), (users.models.AdminType('PROVIDER'), 'PROVIDER')], max_length=50)),
                ('user_type', models.CharField(choices=[(users.models.UserType('STUDENT'), 'STUDENT'), (users.models.UserType('PERSONNEL'), 'PERSONNEL'), (users.models.UserType('GUEST'), 'GUEST')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
