# Generated by Django 2.2.4 on 2019-09-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='notify_at',
        ),
        migrations.AlterField(
            model_name='programslotrecord',
            name='type',
            field=models.CharField(choices=[('RESERVE', 'RESERVE'), ('WAITING', 'WAITING')], max_length=50),
        ),
    ]
